name: Create debian package

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
    branches: [ "*" ]

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          before-build-hook: DEBEMAIL="Robert Burger <robert.burger@dlr.de>" gbp dch
          buildpackage-opts: --build=binary --no-sign
